/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jwl_hellondk_JniTest */

#ifndef _Included_jwl_hellondk_JniTest
#define _Included_jwl_hellondk_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jwl_hellondk_JniTest
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jwl_hellondk_JniTest_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
